# Generated by Django 5.2.5 on 2025-09-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_empresa_cuit_empresa_descripcion_empresa_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='participacion_opciones',
            field=models.CharField(max_length=50, verbose_name='¿Cómo les gustaría participar?'),
        ),
    ]
