# Generated by Django 5.2.5 on 2025-09-20 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_empresa_participacion_opciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistente',
            name='representante_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miembros_representados', to='api.asistente', verbose_name='Representante del Grupo'),
        ),
    ]
