# Generated by Django 5.2.5 on 2025-09-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_asistente_representante_grupo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disertante',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='programa',
            name='categoria',
            field=models.CharField(choices=[('TECNOLOGIA', 'Tecnologia'), ('LOGISTICA', 'Logistica'), ('PUERTOS/COMERCIO EXTERIOR', 'Puertos/Comercio Exterior'), ('E-COMMERS', 'E-Commers'), ('SUPPLY CHAIN', 'Supply Chain'), ('CAPITAL HUMANO', 'Capital Humano'), ('RADIO', 'Radio'), ('SUSTENTABILIDAD', 'Sustentabilidad'), ('TRANSPORTE', 'Transporte')], default='LOGÍSTICA', max_length=30, verbose_name='Categoría'),
        ),
    ]
