# Generated by Django 5.2.5 on 2025-09-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_disertante_options_alter_programa_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cargo_contacto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo que cumple en la empresa / institución'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='celular_contacto',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de celular de contacto'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico de la persona de contacto'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre_contacto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre completo de la persona de contacto'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='participacion_opciones',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Cómo les gustaría participar?'),
        ),
    ]
