# Generated by Django 5.2.5 on 2025-09-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_empresa_cargo_contacto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nombre_empresa']},
        ),
        migrations.AddField(
            model_name='disertante',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='Perfil de LinkedIn'),
        ),
    ]
