# Generated by Django 5.2.5 on 2025-09-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_empresa_options_disertante_linkedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCongreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda_confirmada', models.BooleanField(default=False, verbose_name='¿Agenda confirmada?')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
