# Generated by Django 5.2.5 on 2025-09-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_configuracioncongreso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracionCongreso',
        ),
        migrations.AddField(
            model_name='asistente',
            name='rol_especifico',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rol Específico'),
        ),
        migrations.AlterField(
            model_name='asistente',
            name='dni',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='asistente',
            name='profile_type',
            field=models.CharField(choices=[('VISITOR', 'Visitante'), ('STUDENT', 'Estudiante'), ('TEACHER', 'Docente'), ('PROFESSIONAL', 'Profesional'), ('GROUP_REPRESENTATIVE', 'Representante de Grupo'), ('GRADUADO', 'Graduado'), ('OTRO', 'Otro')], max_length=30, verbose_name='Tipo de Perfil'),
        ),
    ]
