# Generated by Django 5.2.5 on 2025-09-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_configuracioncongreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistente',
            name='dni',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='DNI'),
        ),
    ]
