# Generated by Django 5.2.5 on 2025-09-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_asistente_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='disertante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='ponencias/', verbose_name='Foto (subida)'),
        ),
    ]
