# Generated by Django 5.2.5 on 2025-09-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_disertante_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistente',
            name='profile_type',
            field=models.CharField(choices=[('VISITOR', 'Visitante'), ('STUDENT', 'Estudiante'), ('TEACHER', 'Docente'), ('PROFESSIONAL', 'Profesional'), ('PRESS', 'Prensa'), ('GROUP_REPRESENTATIVE', 'Representante de Grupo'), ('GRADUADO', 'Graduado'), ('OTRO', 'Otro')], max_length=30, verbose_name='Tipo de Perfil'),
        ),
    ]
