# Generated by Django 5.2.5 on 2025-10-25 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_asistente_profile_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='disertante',
        ),
        migrations.AddField(
            model_name='programa',
            name='disertante_old',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas_old', to='api.disertante', verbose_name='Disertante (legacy)'),
        ),
        migrations.AddField(
            model_name='programa',
            name='disertantes',
            field=models.ManyToManyField(blank=True, related_name='programas', to='api.disertante', verbose_name='Disertantes'),
        ),
    ]
