# Generated by Django 5.2.5 on 2025-10-25 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_migrate_disertante_to_disertantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='disertante_old',
        ),
    ]
