# Generated by Django 5.2.5 on 2025-10-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_programa_disertante_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistente',
            name='dni_update_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Token de actualización de DNI'),
        ),
    ]
