# Generated by Django 5.2.5 on 2025-10-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_asistente_dni_update_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistente',
            name='dni_email_sent',
            field=models.BooleanField(default=False, verbose_name='Email de solicitud DNI enviado'),
        ),
        migrations.AddField(
            model_name='asistente',
            name='dni_email_sent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha envío email DNI'),
        ),
    ]
