# Generated by Django 5.2.5 on 2025-11-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_asistente_dni_email_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistente',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de celular'),
        ),
    ]
