# Generated by Django 5.2.5 on 2026-03-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_asistente_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostulacionDisertante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=200, verbose_name='Nombre y Apellido')),
                ('dni', models.CharField(max_length=32, verbose_name='DNI / Documento')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contacto')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('ciudad_provincia', models.CharField(max_length=255, verbose_name='Ciudad y Provincia')),
                ('profesion_cargo', models.CharField(max_length=255, verbose_name='Profesión / Cargo actual')),
                ('empresa_institucion', models.CharField(max_length=255, verbose_name='Empresa / Institución a la que pertenece')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn u otra red profesional')),
                ('titulo_charla', models.CharField(max_length=255, verbose_name='Título de la exposición')),
                ('ejes_tematicos', models.JSONField(blank=True, default=list, verbose_name='Eje temático al que se vincula (Array de strings)')),
                ('eje_otro', models.TextField(blank=True, null=True, verbose_name='Otro eje temático')),
                ('resumen_charla', models.TextField(verbose_name='Resumen de la charla (máx. 300 palabras)')),
                ('objetivos_charla', models.TextField(verbose_name='Objetivos de la exposición')),
                ('publico_dirigido', models.JSONField(default=list, verbose_name='Público al que está dirigida (Array de strings)')),
                ('modalidad', models.JSONField(default=list, verbose_name='Formato preferido (Array de strings)')),
                ('participacion_tipo', models.JSONField(default=list, verbose_name='Tipo de participación (Array de strings)')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20, verbose_name='Estado de la postulación')),
                ('acepta_tyc', models.BooleanField(default=False, verbose_name='Declaro que la información es verídica y acepto TyC')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_postulacion'],
            },
        ),
        migrations.AddField(
            model_name='asistente',
            name='terminos_aceptados',
            field=models.BooleanField(default=False, verbose_name='Acepta Términos y Condiciones'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='acciones_stand',
            field=models.TextField(blank=True, null=True, verbose_name='Acciones de difusión/sorteos en el stand'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='acepta_tyc',
            field=models.BooleanField(default=False, verbose_name='Acepta Términos y Condiciones'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='computadora_o_pantalla',
            field=models.BooleanField(default=False, verbose_name='¿Llevará pantalla o equipo audiovisual propio?'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estructura_adicional',
            field=models.TextField(blank=True, null=True, verbose_name='Estructura adicional (back, banners, etc.)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='gazebo_propio',
            field=models.BooleanField(default=False, verbose_name='¿Cuenta con gazebo propio?'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='participo_edicion_anterior',
            field=models.BooleanField(default=False, verbose_name='¿Participó en la edición anterior?'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='requiere_electricidad',
            field=models.BooleanField(default=False, verbose_name='¿Requiere conexión eléctrica para TV/PC?'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='rubro_logistico',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rubro dentro del sector logístico'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_mobiliario',
            field=models.CharField(blank=True, choices=[('Mesa y dos sillas', 'Mesa y dos sillas'), ('Solo mesa', 'Solo mesa'), ('Solo dos sillas', 'Solo dos sillas'), ('Ninguno', 'No requiere mobiliario')], max_length=50, null=True, verbose_name='¿Requiere mobiliario?'),
        ),
    ]
