# Generated by Django 5.2.5 on 2026-03-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_postulaciondisertante_asistente_terminos_aceptados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logos_empresas/', verbose_name='Logo de la empresa'),
        ),
    ]
