# Generated by Django 5.2.5 on 2026-03-09 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_empresa_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(unique=True, verbose_name='Año de la Edición')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('activa', models.BooleanField(default=False, verbose_name='¿Es la edición actual?')),
            ],
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='asistente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='api.asistente'),
        ),
        migrations.CreateModel(
            name='DetalleDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=255, null=True, verbose_name='Institución')),
                ('career_taught', models.CharField(blank=True, max_length=255, null=True, verbose_name='Carrera que dicta')),
                ('asistente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_docente', to='api.asistente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_unab_student', models.BooleanField(default=False, verbose_name='¿Perteneces a la UNaB?')),
                ('institution', models.CharField(blank=True, max_length=255, null=True, verbose_name='Institución (estudio o trabajo)')),
                ('career', models.CharField(blank=True, max_length=255, null=True, verbose_name='Carrera que cursas')),
                ('year_of_study', models.IntegerField(blank=True, null=True, verbose_name='Año que cursas')),
                ('asistente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_estudiante', to='api.asistente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la institución o grupo')),
                ('group_municipality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Partido al que pertenece la institución')),
                ('group_size', models.IntegerField(default=0, verbose_name='Cantidad de personas en el grupo')),
                ('asistente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_grupo', to='api.asistente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Área de trabajo')),
                ('occupation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo')),
                ('asistente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_profesional', to='api.asistente')),
            ],
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='edicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscripciones', to='api.edicion'),
        ),
    ]
