# Generated by Django 5.2.5 on 2026-03-09 16:29

from django.db import migrations

def migrate_asistentes(apps, schema_editor):
    Asistente = apps.get_model('api', 'Asistente')
    Inscripcion = apps.get_model('api', 'Inscripcion')
    Edicion = apps.get_model('api', 'Edicion')
    DetalleEstudiante = apps.get_model('api', 'DetalleEstudiante')
    DetalleDocente = apps.get_model('api', 'DetalleDocente')
    DetalleProfesional = apps.get_model('api', 'DetalleProfesional')
    DetalleGrupo = apps.get_model('api', 'DetalleGrupo')

    # Create editions
    edicion_2025, _ = Edicion.objects.get_or_create(
        anio=2025,
        defaults={'nombre': 'Congreso de Logística 2025', 'activa': False}
    )
    edicion_2026, _ = Edicion.objects.get_or_create(
        anio=2026,
        defaults={'nombre': 'Congreso de Logística 2026', 'activa': True}
    )

    # Move existing Inscripcion to 2025
    Inscripcion.objects.filter(edicion__isnull=True).update(edicion=edicion_2025)

    # Migrate Asistente fields to Detalle models
    for asistente in Asistente.objects.all():
        profile = asistente.profile_type

        if profile == 'STUDENT':
            DetalleEstudiante.objects.get_or_create(
                asistente=asistente,
                defaults={
                    'is_unab_student': asistente.is_unab_student or False,
                    'institution': asistente.institution,
                    'career': asistente.career,
                    'year_of_study': asistente.year_of_study,
                }
            )
        elif profile == 'TEACHER':
            DetalleDocente.objects.get_or_create(
                asistente=asistente,
                defaults={
                    'institution': asistente.institution,
                    'career_taught': asistente.career_taught,
                }
            )
        elif profile == 'PROFESSIONAL':
            DetalleProfesional.objects.get_or_create(
                asistente=asistente,
                defaults={
                    'work_area': asistente.work_area,
                    'occupation': asistente.occupation,
                }
            )
        elif profile == 'GROUP_REPRESENTATIVE':
            DetalleGrupo.objects.get_or_create(
                asistente=asistente,
                defaults={
                    'group_name': asistente.group_name,
                    'group_municipality': asistente.group_municipality,
                    'group_size': asistente.group_size or 0,
                }
            )

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_edicion_alter_inscripcion_asistente_detalledocente_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_asistentes, reverse_code=migrations.RunPython.noop),
    ]
