# Generated by Django 5.2.5 on 2026-03-09 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20260309_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistente',
            name='career',
        ),
        migrations.RemoveField(
            model_name='asistente',
            name='career_taught',
        ),
        migrations.RemoveField(
            model_name='asistente',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='asistente',
            name='group_municipality',
        ),
        migrations.RemoveField(
            model_name='asistente',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='asistente',
            name='group_size',
        ),
        migrations.RemoveField(
            model_name='asistente',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='asistente',
            name='is_unab_student',
        ),
        migrations.RemoveField(
            model_name='asistente',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='asistente',
            name='work_area',
        ),
        migrations.RemoveField(
            model_name='asistente',
            name='year_of_study',
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='edicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='api.edicion'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('asistente', 'edicion')},
        ),
    ]
