# Generated by Django 5.2.5 on 2026-03-09 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_disertante_edicion_disertante_estado_empresa_edicion_and_more'),
    ]

def assign_historical_edicion(apps, schema_editor):
    Edicion = apps.get_model('api', 'Edicion')
    Empresa = apps.get_model('api', 'Empresa')
    Disertante = apps.get_model('api', 'Disertante')
    PostulacionDisertante = apps.get_model('api', 'PostulacionDisertante')

    # Obtener o crear edicion historica (por ejemplo, 2025)
    edicion_historica, created = Edicion.objects.get_or_create(
        anio=2025,
        defaults={'nombre': '1° Congreso UNAB Logística 2025', 'activa': False}
    )

    # Actualizar Empresas existentes
    Empresa.objects.filter(edicion__isnull=True).update(edicion=edicion_historica, estado='APROBADO')
    
    # Actualizar Disertantes existentes
    Disertante.objects.filter(edicion__isnull=True).update(edicion=edicion_historica, estado='APROBADO')
    
    # Actualizar Postulaciones existentes
    PostulacionDisertante.objects.filter(edicion__isnull=True).update(edicion=edicion_historica)
    # Nota: PostulacionDisertante ya tenía un campo 'estado', así que no pusimos default a PENDIENTE sino que mantuvimos el que tenían.

def revert_assignment(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_disertante_edicion_disertante_estado_empresa_edicion_and_more'),
    ]

    operations = [
        migrations.RunPython(assign_historical_edicion, revert_assignment)
    ]
