# Generated by Django 5.2.5 on 2026-03-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_assign_edicion_disertantes_empresas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Dashboard de Estadísticas',
                'verbose_name_plural': '📊 Dashboards de Estadísticas',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro'),
        ),
    ]
