# Generated by Django 5.2.5 on 2026-03-13 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_dashboard_empresa_fecha_registro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asistente',
            name='ciudad_provincia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ciudad / Provincia'),
        ),
        migrations.AddField(
            model_name='asistente',
            name='disertante_vinculado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistente_disertante', to='api.disertante', verbose_name='Disertante vinculado'),
        ),
        migrations.AddField(
            model_name='asistente',
            name='empresa_vinculada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representantes_asistente', to='api.empresa', verbose_name='Empresa vinculada'),
        ),
        migrations.AddField(
            model_name='asistente',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='detallegrupo',
            name='institution_or_workplace',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Institución o lugar de trabajo del representante'),
        ),
        migrations.AddField(
            model_name='detallegrupo',
            name='tipo_grupo',
            field=models.JSONField(default=list, help_text='Opciones: ESCOLAR, UNIVERSITARIO, INSTITUCIONAL, EMPRESARIAL, OTRO', verbose_name='Tipo de grupo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cantidad_representantes',
            field=models.IntegerField(blank=True, help_text='Editable hasta el día del evento', null=True, verbose_name='Cantidad de representantes que asistirán'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='notas_admin',
            field=models.TextField(blank=True, null=True, verbose_name='Notas internas (solo admin)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero_stand',
            field=models.CharField(blank=True, help_text='Asignado y editable desde el admin', max_length=20, null=True, verbose_name='Número de stand asignado'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='revisada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Revisada por'),
        ),
        migrations.AddField(
            model_name='postulaciondisertante',
            name='duracion_estimada',
            field=models.IntegerField(default=30, help_text='Por defecto 30 min. Editable desde el admin.', verbose_name='Duración estimada (minutos)'),
        ),
        migrations.AddField(
            model_name='postulaciondisertante',
            name='experiencia_previa',
            field=models.TextField(blank=True, null=True, verbose_name='Experiencia previa disertando'),
        ),
        migrations.AddField(
            model_name='postulaciondisertante',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión'),
        ),
        migrations.AddField(
            model_name='postulaciondisertante',
            name='foto_perfil',
            field=models.FileField(blank=True, null=True, upload_to='postulaciones_fotos/', verbose_name='Foto de perfil (opcional)'),
        ),
        migrations.AddField(
            model_name='postulaciondisertante',
            name='notas_admin',
            field=models.TextField(blank=True, null=True, verbose_name='Notas internas (solo admin)'),
        ),
        migrations.AddField(
            model_name='postulaciondisertante',
            name='requiere_equipamiento',
            field=models.TextField(blank=True, null=True, verbose_name='Equipamiento requerido (proyector, micrófono, etc.)'),
        ),
        migrations.AddField(
            model_name='postulaciondisertante',
            name='revisada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulaciones_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Revisada por'),
        ),
        migrations.AlterField(
            model_name='asistente',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='postulaciondisertante',
            name='dni',
            field=models.CharField(max_length=8, verbose_name='DNI / Documento'),
        ),
        migrations.CreateModel(
            name='InscripcionPrensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=200, verbose_name='Nombre y Apellido')),
                ('dni', models.CharField(max_length=8, verbose_name='DNI')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contacto')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('ciudad_provincia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ciudad / Provincia')),
                ('tipo_perfil', models.CharField(choices=[('PERIODISTA', 'Periodista / Medio de comunicación'), ('INFLUENCER', 'Influencer / Creador de contenido digital'), ('FOTOGRAFO', 'Fotógrafo / Camarógrafo'), ('BLOGGER', 'Blogger'), ('PODCASTER', 'Podcaster'), ('OTRO', 'Otro perfil mediático')], max_length=20, verbose_name='Tipo de perfil')),
                ('medio_o_canal', models.CharField(max_length=255, verbose_name='Medio o canal')),
                ('url_perfil_red', models.URLField(blank=True, null=True, verbose_name='URL perfil red social (Instagram, YouTube, TikTok, etc.)')),
                ('url_sitio_medio', models.URLField(blank=True, null=True, verbose_name='URL sitio web del medio')),
                ('seguidores_aprox', models.IntegerField(blank=True, null=True, verbose_name='Seguidores aproximados (solo influencers)')),
                ('notas_admin', models.TextField(blank=True, null=True, verbose_name='Notas internas (solo admin)')),
                ('acepta_tyc', models.BooleanField(default=False, verbose_name='Acepta Términos y Condiciones')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('edicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_prensa', to='api.edicion')),
            ],
            options={
                'verbose_name': 'Inscripción Prensa/Influencer',
                'verbose_name_plural': 'Inscripciones Prensa/Influencers',
                'ordering': ['-fecha_inscripcion'],
            },
        ),
        migrations.AddField(
            model_name='asistente',
            name='prensa_vinculada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistente_prensa', to='api.inscripcionprensa', verbose_name='Inscripción prensa vinculada'),
        ),
    ]
