# Generated by Django 5.2.5 on 2026-03-20 00:55

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_add_missing_fields_and_prensa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edicion',
            options={'verbose_name': 'Edición', 'verbose_name_plural': 'Ediciones'},
        ),
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'verbose_name': 'Inscripción', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AlterField(
            model_name='asistente',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='asistente',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de celular'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='pdf_generado',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='certificados/', verbose_name='PDF Generado'),
        ),
        migrations.AlterField(
            model_name='inscripcionprensa',
            name='dni',
            field=models.CharField(max_length=20, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='inscripcionprensa',
            name='telefono',
            field=models.CharField(max_length=50, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='postulaciondisertante',
            name='dni',
            field=models.CharField(max_length=20, verbose_name='DNI / Documento'),
        ),
        migrations.AlterField(
            model_name='postulaciondisertante',
            name='telefono',
            field=models.CharField(max_length=50, verbose_name='Teléfono'),
        ),
    ]
