# Generated by Django 5.2.5 on 2026-03-20 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_edicion_options_alter_inscripcion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='edicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='api.edicion'),
        ),
    ]
