# Generated by Django 5.2.5 on 2026-03-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_programa_edicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistente',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='asistente',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de celular'),
        ),
        migrations.AlterField(
            model_name='inscripcionprensa',
            name='dni',
            field=models.CharField(max_length=8, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='inscripcionprensa',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='postulaciondisertante',
            name='dni',
            field=models.CharField(max_length=8, verbose_name='DNI / Documento'),
        ),
        migrations.AlterField(
            model_name='postulaciondisertante',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
    ]
