# Generated by Django 5.2.5 on 2026-03-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_asistente_dni_alter_asistente_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembrogrupo',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro'),
        ),
    ]
