# Generated by Django 5.2.5 on 2026-03-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_miembrogrupo_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='email_enviado',
            field=models.BooleanField(default=False, verbose_name='Email Enviado'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='intentos',
            field=models.IntegerField(default=0, verbose_name='Intentos de Envío'),
        ),
    ]
