# Generated by Django 5.2.5 on 2026-03-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_certificado_email_enviado_certificado_fecha_envio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallegrupo',
            name='tipo_grupo',
            field=models.TextField(default='', help_text='Opciones JSON: ESCOLAR, UNIVERSITARIO, INSTITUCIONAL, EMPRESARIAL, OTRO', verbose_name='Tipo de grupo'),
        ),
        migrations.AlterField(
            model_name='postulaciondisertante',
            name='ejes_tematicos',
            field=models.TextField(blank=True, default='', verbose_name='Eje temático al que se vincula (JSON String)'),
        ),
        migrations.AlterField(
            model_name='postulaciondisertante',
            name='modalidad',
            field=models.TextField(default='', verbose_name='Formato preferido (JSON String)'),
        ),
        migrations.AlterField(
            model_name='postulaciondisertante',
            name='participacion_tipo',
            field=models.TextField(default='', verbose_name='Tipo de participación (JSON String)'),
        ),
        migrations.AlterField(
            model_name='postulaciondisertante',
            name='publico_dirigido',
            field=models.TextField(default='', verbose_name='Público al que está dirigida (JSON String)'),
        ),
    ]
