# Generated by Django 5.2.5 on 2026-03-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_detallegrupo_tipo_grupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistente',
            name='prensa_links',
            field=models.TextField(blank=True, null=True, verbose_name='Links de web, redes o canales de difusión'),
        ),
        migrations.AddField(
            model_name='asistente',
            name='prensa_medio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Medio al que pertenece'),
        ),
        migrations.AlterField(
            model_name='asistente',
            name='profile_type',
            field=models.CharField(choices=[('VISITOR', 'Visitante'), ('STUDENT', 'Estudiante'), ('TEACHER', 'Docente'), ('PROFESSIONAL', 'Profesional'), ('PRESS', 'Prensa/Influencer'), ('GROUP_REPRESENTATIVE', 'Representante de Grupo'), ('GRADUADO', 'Graduado'), ('OTRO', 'Otro')], max_length=30, verbose_name='Tipo de Perfil'),
        ),
    ]
