# Generated by Django 5.2.5 on 2026-04-01 15:42

from django.db import migrations, models
from django.utils import timezone

def migrate_attendance_data(apps, schema_editor):
    Asistente = apps.get_model('api', 'Asistente')
    Inscripcion = apps.get_model('api', 'Inscripcion')
    Edicion = apps.get_model('api', 'Edicion')
    
    # Obtener edición activa (del 2026 supuestamente)
    edicion_activa = Edicion.objects.filter(activa=True).first()
    if not edicion_activa:
        # Si no hay activa, buscamos la de mayor año como fallback
        edicion_activa = Edicion.objects.order_by('-anio').first()
    
    if not edicion_activa:
        return

    # Migrar datos de Asistente a Inscripcion
    # Solo para aquellos que tengan asistencia confirmada
    asistentes_confirmados = Asistente.objects.filter(asistencia_confirmada=True)
    for asistente in asistentes_confirmados:
        # Buscar o crear la inscripción para este asistente en la edición activa
        inscripcion, created = Inscripcion.objects.get_or_create(
            asistente=asistente, 
            edicion=edicion_activa
        )
        inscripcion.asistencia_confirmada = True
        inscripcion.fecha_confirmacion = asistente.fecha_confirmacion or timezone.now()
        inscripcion.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_asistente_prensa_links_asistente_prensa_medio_and_more'),
    ]

    operations = [
        # 1. Agregar campos a Inscripcion
        migrations.AddField(
            model_name='inscripcion',
            name='asistencia_confirmada',
            field=models.BooleanField(default=False, verbose_name='Asistencia Confirmada'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='fecha_confirmacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación'),
        ),
        
        # 2. MIGRAR DATOS
        migrations.RunPython(migrate_attendance_data),

        # 3. Eliminar campos de Asistente
        migrations.RemoveField(
            model_name='asistente',
            name='asistencia_confirmada',
        ),
        migrations.RemoveField(
            model_name='asistente',
            name='fecha_confirmacion',
        ),
        
        # 4. Otros cambios
        migrations.AlterField(
            model_name='empresa',
            name='participacion_opciones',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='¿Cómo les gustaría participar?'),
        ),
    ]
