# Generated by Django 5.2.5 on 2026-04-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_add_indexes_inscripcion'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inscripcion',
            name='api_inscri_edicion_cf0db8_idx',
        ),
        migrations.RemoveIndex(
            model_name='inscripcion',
            name='api_inscri_fecha_i_7f8486_idx',
        ),
        migrations.AddField(
            model_name='asistente',
            name='comision',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comisión / Curso'),
        ),
    ]
