# Generated by Django 5.2.5 on 2026-04-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_inscripcion_api_inscri_edicion_cf0db8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='desea_alertas_laborales',
            field=models.BooleanField(default=False, verbose_name='¿Desea recibir alertas laborales?'),
        ),
    ]
