# Generated by Django 5.1.2 on 2026-04-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_inscripcion_desea_alertas_laborales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIO_BC', 'Envío de Bases y Condiciones'), ('PENDIENTE_PAGO', 'Pendiente de Pago'), ('CONFIRMADA', 'Confirmada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
    ]
