# Generated by Django 5.1.2 on 2026-04-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_empresa_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='difusion_redes',
            field=models.TextField(blank=True, null=True, verbose_name='¿Qué les gustaría que contemos en nuestras redes de ustedes?'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='¿Quiénes son y a qué se dedican?'),
        ),
    ]
