# Generated by Django 5.1.2 on 2026-04-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_empresa_difusion_redes_alter_empresa_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='es_sponsor',
            field=models.BooleanField(default=False, verbose_name='¿Es Patrocinador?'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='youtube_video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Video de YouTube'),
        ),
    ]
