# Generated by Django 5.1.2 on 2026-04-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_empresa_es_sponsor_empresa_youtube_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disertante',
            name='linkedin',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Perfil de LinkedIn'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='sitio_web',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Sitio Web de la empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='youtube_video_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='URL del Video de YouTube'),
        ),
        migrations.AlterField(
            model_name='inscripcionprensa',
            name='url_perfil_red',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='URL perfil red social (Instagram, YouTube, TikTok, etc.)'),
        ),
        migrations.AlterField(
            model_name='inscripcionprensa',
            name='url_sitio_medio',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='URL sitio web del medio'),
        ),
        migrations.AlterField(
            model_name='postulaciondisertante',
            name='linkedin',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='LinkedIn u otra red profesional'),
        ),
    ]
