# Generated by Django 5.1.2 on 2026-05-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_historicalasistente_historicalempresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistente',
            name='first_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='asistente',
            name='last_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email_contacto',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Correo electrónico de la persona de contacto'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre_empresa',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nombre de la empresa o institución'),
        ),
        migrations.AlterField(
            model_name='historicalasistente',
            name='first_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='historicalasistente',
            name='last_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='email_contacto',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Correo electrónico de la persona de contacto'),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='nombre_empresa',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nombre de la empresa o institución'),
        ),
        migrations.AlterField(
            model_name='historicalpostulaciondisertante',
            name='dni',
            field=models.CharField(db_index=True, max_length=8, verbose_name='DNI / Documento'),
        ),
        migrations.AlterField(
            model_name='historicalpostulaciondisertante',
            name='fecha_postulacion',
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='inscripcionprensa',
            name='dni',
            field=models.CharField(db_index=True, max_length=8, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='inscripcionprensa',
            name='fecha_inscripcion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='postulaciondisertante',
            name='dni',
            field=models.CharField(db_index=True, max_length=8, verbose_name='DNI / Documento'),
        ),
        migrations.AlterField(
            model_name='postulaciondisertante',
            name='fecha_postulacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
