# Generated by Django 5.1.2 on 2026-05-23 17:16

import django.db.models.deletion
from django.db import migrations, models

def migrate_attendance_and_certificates(apps, schema_editor):
    Edicion = apps.get_model('api', 'Edicion')
    Certificado = apps.get_model('api', 'Certificado')
    Inscripcion = apps.get_model('api', 'Inscripcion')

    # 1. Buscar o crear la edición 2025
    edicion_2025 = Edicion.objects.filter(anio=2025).first()
    if not edicion_2025:
        edicion_2025 = Edicion.objects.create(anio=2025, nombre="Congreso de Logística 2025", activa=False)

    # 2. Asociar todos los certificados históricos (creados hasta hoy) a 2025
    Certificado.objects.filter(edicion__isnull=True).update(edicion=edicion_2025)

    # 3. Limpiar asistencias erróneas de la edición activa 2026
    edicion_activa = Edicion.objects.filter(activa=True).first()
    if edicion_activa:
        # Poner asistencia en False y limpiar la fecha de confirmación
        Inscripcion.objects.filter(edicion=edicion_activa).update(
            asistencia_confirmada=False,
            fecha_confirmacion=None
        )

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_asistente_first_name_alter_asistente_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificado',
            options={'verbose_name': 'Certificado', 'verbose_name_plural': 'Certificados'},
        ),
        migrations.AddField(
            model_name='certificado',
            name='edicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='api.edicion'),
        ),
        # Ejecutar la migración de datos ANTES de AlterUniqueTogether
        migrations.RunPython(migrate_attendance_and_certificates),
        migrations.AlterUniqueTogether(
            name='certificado',
            unique_together={('asistente', 'edicion', 'tipo_certificado')},
        ),
    ]
