# Generated by Django 5.1.2 on 2026-08-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_certificado_edicion_clean_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='disertante',
            name='empresa_institucion',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Empresa / Institución (Representante de)'),
        ),
        migrations.AddField(
            model_name='programa',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado')], default='PUBLICADO', max_length=20, verbose_name='Estado de publicación'),
        ),
        migrations.AlterField(
            model_name='disertante',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='Biografía (opcional)'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='aula',
            field=models.CharField(blank=True, choices=[('Aula Magna', 'Aula Magna'), ('Aula 1', 'Aula 1'), ('Aula 2', 'Aula 2'), ('Aula 3', 'Aula 3'), ('Aula 4', 'Aula 4'), ('Aula 5', 'Aula 5'), ('Aula 6', 'Aula 6'), ('Aula 7', 'Aula 7'), ('Aula 8', 'Aula 8'), ('Aula 9', 'Aula 9'), ('Aula 10', 'Aula 10')], default='Aula Magna', max_length=30, verbose_name='Aula'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='categoria',
            field=models.CharField(choices=[('TECNOLOGIA', 'Tecnologia'), ('LOGISTICA', 'Logistica'), ('PUERTOS/COMERCIO EXTERIOR', 'Puertos/Comercio Exterior'), ('E-COMMERS', 'E-Commers'), ('SUPPLY CHAIN', 'Supply Chain'), ('CAPITAL HUMANO', 'Capital Humano'), ('RADIO', 'Radio'), ('SUSTENTABILIDAD', 'Sustentabilidad'), ('TRANSPORTE', 'Transporte'), ('INSTITUCIONAL', 'Institucional / Apertura / Cierre'), ('NETWORKING', 'Networking / Coffee Break'), ('WORKSHOP', 'Taller / Demo en vivo')], default='LOGISTICA', max_length=30, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='dia',
            field=models.DateField(default='2026-11-07', verbose_name='Día del Evento'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Fin'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Inicio'),
        ),
    ]
