# Generated by Django 5.1.2 on 2026-10-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_create_postulacion_german_menichetti'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEnvioEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.EmailField(max_length=254, verbose_name='Email Destinatario')),
                ('asunto', models.CharField(max_length=255, verbose_name='Asunto')),
                ('tipo_email', models.CharField(default='general', max_length=50, verbose_name='Tipo de Email')),
                ('exitoso', models.BooleanField(default=False, verbose_name='¿Exitoso?')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error / Traceback')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
            ],
            options={
                'verbose_name': 'Log de Envío de Email',
                'verbose_name_plural': 'Logs de Envíos de Email',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.AlterField(
            model_name='historicalpostulaciondisertante',
            name='ciudad_provincia',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ciudad y Provincia'),
        ),
        migrations.AlterField(
            model_name='historicalpostulaciondisertante',
            name='dni',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='DNI / Documento'),
        ),
        migrations.AlterField(
            model_name='historicalpostulaciondisertante',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email de contacto'),
        ),
        migrations.AlterField(
            model_name='historicalpostulaciondisertante',
            name='empresa_institucion',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Empresa / Institución a la que pertenece (opcional)'),
        ),
        migrations.AlterField(
            model_name='historicalpostulaciondisertante',
            name='objetivos_charla',
            field=models.TextField(blank=True, default='', verbose_name='Objetivos de la exposición'),
        ),
        migrations.AlterField(
            model_name='historicalpostulaciondisertante',
            name='profesion_cargo',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Profesión / Cargo actual'),
        ),
        migrations.AlterField(
            model_name='historicalpostulaciondisertante',
            name='resumen_charla',
            field=models.TextField(blank=True, default='', verbose_name='Resumen de la charla (máx. 300 palabras)'),
        ),
        migrations.AlterField(
            model_name='historicalpostulaciondisertante',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='postulaciondisertante',
            name='empresa_institucion',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Empresa / Institución a la que pertenece (opcional)'),
        ),
    ]
