# Generated by Django 5.1.2 on 2026-10-05 15:02

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_logenvioemail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPersonalEmpresa',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(db_index=True, max_length=20, verbose_name='DNI / Documento')),
                ('cargo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Cargo / Puesto en la empresa')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono / Celular')),
                ('acreditado', models.BooleanField(default=False, verbose_name='¿Acreditado en el evento?')),
                ('fecha_acreditacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de acreditación in-situ')),
                ('fecha_registro', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de registro')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('asistente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.asistente', verbose_name='Asistente Vinculado')),
                ('empresa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.empresa', verbose_name='Empresa / Institución')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Personal de Empresa',
                'verbose_name_plural': 'historical Personal de Empresas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PersonalEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(db_index=True, max_length=20, verbose_name='DNI / Documento')),
                ('cargo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Cargo / Puesto en la empresa')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono / Celular')),
                ('acreditado', models.BooleanField(default=False, verbose_name='¿Acreditado en el evento?')),
                ('fecha_acreditacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de acreditación in-situ')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('asistente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_empresa_vinculado', to='api.asistente', verbose_name='Asistente Vinculado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='api.empresa', verbose_name='Empresa / Institución')),
            ],
            options={
                'verbose_name': 'Personal de Empresa',
                'verbose_name_plural': 'Personal de Empresas',
                'ordering': ['apellido', 'nombre'],
                'unique_together': {('empresa', 'dni')},
            },
        ),
    ]
