# Generated by Django 5.1.2 on 2026-10-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_historicalpersonalempresa_personalempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistente',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='historicalasistente',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
    ]
