"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from typing import Dict, Any

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-2zba+jiuh_gqthifa5*y7illxqrj8oz03yv005)g0-wfpi@o1d')

# SECURITY WARNING: don't run with debug turned on in production!
if os.getenv('DJANGO_ENV') == 'development':
    DEBUG = True
else:
    DEBUG = False

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '0.0.0.0',
    'www.congresologistica.unab.edu.ar',
    'congresologistica.unab.edu.ar',
    '170.210.44.238'
]




# Application definition

from dotenv import load_dotenv # type: ignore
# Cargar variables de entorno desde .env en la raíz del backend
dotenv_path = os.path.join(BASE_DIR, '.env')
if os.path.exists(dotenv_path):
    load_dotenv(dotenv_path)
else:
    print(f"[WARNING] No se encontró el archivo .env en {dotenv_path}")



INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'



# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'congreso_2026'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'OPTIONS': {
            'client_encoding': 'SQL_ASCII',
        }
    }
}

# Fallback a SQLite solo si se especifica explícitamente para pruebas rápidas
if os.getenv('USE_SQLITE') == 'True':
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': str(BASE_DIR / 'db.sqlite3'),
    }


# Password validation
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =================== CONFIGURACIÓN DE EMAIL (GMAIL SMTP) ===================
# Asegúrate de tener las siguientes variables en tu .env:
# EMAIL_HOST_USER=contactofolkode@gmail.com
# EMAIL_HOST_PASSWORD=tu_contraseña_o_app_password
# EMAIL_HOST=smtp.gmail.com
# EMAIL_PORT=587
# EMAIL_USE_TLS=True

# Backend de email para producción
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# Para probar en local, comenta la línea de arriba y descomenta la siguiente:
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ['true', '1', 'yes']
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# Validación básica para evitar errores comunes
if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
    print("[ERROR] EMAIL_HOST_USER o EMAIL_HOST_PASSWORD no están definidos en el .env. El envío de emails fallará.")
if EMAIL_HOST_USER and '@gmail.com' in EMAIL_HOST_USER and EMAIL_HOST_PASSWORD and len(EMAIL_HOST_PASSWORD) < 16:
    print("[ADVERTENCIA] Gmail requiere una contraseña de aplicación (16 caracteres) si tienes 2FA activado. Verifica tu .env.")


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'

# En desarrollo, asegúrate de que Django busque los archivos estáticos en las apps
if os.getenv('DJANGO_ENV') == 'development':
    STATICFILES_DIRS = []
else:
    # En producción, recolectar archivos estáticos aquí
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CORS settings
import socket
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'https://congresologisticaytransporteunab.netlify.app',
    'http://localhost:8080',
    'http://localhost:8081',
    f'http://{socket.gethostbyname(socket.gethostname())}:8080',
    f'http://{socket.gethostbyname(socket.gethostname())}:8081',
    'https://www.congresologistica.unab.edu.ar',
    'https://congresologistica.unab.edu.ar',
]
CORS_ALLOW_ALL_ORIGINS = True
# ¡IMPORTANTE! Se establece en False por seguridad en producción.
# Solo los orígenes en CORS_ALLOWED_ORIGINS podrán acceder a la API.
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Media files (PDFs, imágenes, etc)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# =================== CONFIGURACIÓN DE STORAGE ===================
# Definir configuración por defecto (Local) para evitar InvalidStorageError
STORAGES: Dict[str, Any] = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
    "private": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "LOCATION": os.path.join(BASE_DIR, 'private_media'),
    },
}

SUPABASE_URL = os.getenv('SUPABASE_URL')
SUPABASE_SERVICE_KEY = os.getenv('SUPABASE_SERVICE_KEY')
SUPABASE_PUBLIC_BUCKET = 'congreso-public'
SUPABASE_PRIVATE_BUCKET = 'congreso-private'

# Solo usar Supabase si se solicita explícitamente y están las claves
if os.getenv('USE_SUPABASE_STORAGE') == 'True' and SUPABASE_SERVICE_KEY:
    STORAGES["default"] = {
        "BACKEND": "api.custom_storage.SupabaseStorage",
        "OPTIONS": {
            "bucket_name": SUPABASE_PUBLIC_BUCKET,
            "supabase_url": SUPABASE_URL,
            "supabase_key": SUPABASE_SERVICE_KEY,
            "location": "media",
        },
    }
    STORAGES["private"] = {
        "BACKEND": "api.custom_storage.SupabaseStorage",
        "OPTIONS": {
            "bucket_name": SUPABASE_PRIVATE_BUCKET,
            "supabase_url": SUPABASE_URL,
            "supabase_key": SUPABASE_SERVICE_KEY,
            "location": "certificates",
        },
    }

# =================== SEGURIDAD CSRF Y COOKIES ===================
# Configuración de orígenes confiables para CSRF (aplica tanto en desarrollo como producción)
CSRF_TRUSTED_ORIGINS = [
    "https://www.congresologistica.unab.edu.ar",
    "https://congresologistica.unab.edu.ar",
    "http://localhost:8080",
    "http://localhost:5173",
    "http://127.0.0.1:8080",
    "http://127.0.0.1:5173",
]

# Configuraciones adicionales de seguridad para producción
if not DEBUG:
    # Comentamos estas configuraciones para resolver el problema de CSRF
    # CSRF_COOKIE_SECURE = True  # Requiere HTTPS
    # SESSION_COOKIE_SECURE = True  # Requiere HTTPS
    # CSRF_COOKIE_DOMAIN = '.congresologistica.unab.edu.ar'
    
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    # Configuración para proxy inverso (Nginx)
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Estas configuraciones son críticas para que funcione correctamente (desarrollo y producción)
CSRF_COOKIE_HTTPONLY = False  # Permite que JavaScript acceda a la cookie CSRF
CSRF_COOKIE_SECURE = False  # Permitir en HTTP para desarrollo (cambiar a True en prod con HTTPS)
SESSION_COOKIE_HTTPONLY = True  # Protege la cookie de sesión
CSRF_USE_SESSIONS = False  # Guarda el token CSRF en cookies, no en sesión
CSRF_COOKIE_SAMESITE = 'Lax'  # 'Lax' es un buen compromiso entre seguridad y usabilidad
SESSION_COOKIE_SAMESITE = 'Lax'

# URL del frontend para enlaces en emails
FRONTEND_URL = "https://www.congresologistica.unab.edu.ar"
