# Generated by Django 5.2.5 on 2026-04-07 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0039_remove_inscripcion_api_inscri_edicion_cf0db8_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_puesto', models.CharField(max_length=255, verbose_name='Título del puesto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('requisitos', models.TextField(verbose_name='Requisitos')),
                ('modalidad', models.CharField(choices=[('REMOTO', 'Remoto'), ('PRESENCIAL', 'Presencial'), ('HIBRIDO', 'Híbrido')], default='PRESENCIAL', max_length=20, verbose_name='Modalidad')),
                ('ubicacion', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('canal_postulacion', models.TextField(verbose_name='Canal de postulación')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('EXPIRADO', 'Expirado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_expiracion', models.DateTimeField(verbose_name='Fecha de expiración')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_laborales', to='api.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Oferta Laboral',
                'verbose_name_plural': 'Ofertas Laborales',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
