# Generated by Django 5.1.2 on 2026-04-07 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa_trabajo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostulacionOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('cv', models.FileField(upload_to='cvs_postulaciones/', verbose_name='Currículum Vitae')),
                ('mensaje', models.TextField(blank=True, null=True, verbose_name='Mensaje (opcional)')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de postulación')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='bolsa_trabajo.ofertalaboral', verbose_name='Oferta')),
            ],
            options={
                'verbose_name': 'Postulación a Oferta',
                'verbose_name_plural': 'Postulaciones a Ofertas',
                'ordering': ['-fecha_postulacion'],
            },
        ),
    ]
