# Generated by Django 5.1.2 on 2026-04-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa_trabajo', '0002_postulacionoferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacionoferta',
            name='es_estudiante',
            field=models.BooleanField(default=False, verbose_name='¿Es estudiante?'),
        ),
        migrations.AddField(
            model_name='postulacionoferta',
            name='institucion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Institución'),
        ),
    ]
